/*
 * Copyright (c) 2024, Janet-botan Seungki Kim
 *
 * Janet-pkcs11 is released under the MIT License, see the LICENSE file.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "main.h"
#include "types.h"

#define HASH_SIZE 1500

typedef struct {
    const char *name;
    unsigned long value;
} TypeEntry;

const TypeEntry type_table[] = {
    {"CKA_AC_ISSUER", CKA_AC_ISSUER},
    {"CKA_ALLOWED_MECHANISMS", CKA_ALLOWED_MECHANISMS},
    {"CKA_ALWAYS_AUTHENTICATE", CKA_ALWAYS_AUTHENTICATE},
    {"CKA_ALWAYS_SENSITIVE", CKA_ALWAYS_SENSITIVE},
    {"CKA_APPLICATION", CKA_APPLICATION},
    {"CKA_ATTR_TYPES", CKA_ATTR_TYPES},
    {"CKA_BASE", CKA_BASE},
    {"CKA_BITS_PER_PIXEL", CKA_BITS_PER_PIXEL},
    {"CKA_CERTIFICATE_CATEGORY", CKA_CERTIFICATE_CATEGORY},
    {"CKA_CERTIFICATE_TYPE", CKA_CERTIFICATE_TYPE},
    {"CKA_CHAR_COLUMNS", CKA_CHAR_COLUMNS},
    {"CKA_CHAR_ROWS", CKA_CHAR_ROWS},
    {"CKA_CHAR_SETS", CKA_CHAR_SETS},
    {"CKA_CHECK_VALUE", CKA_CHECK_VALUE},
    {"CKA_CLASS", CKA_CLASS},
    {"CKA_COEFFICIENT", CKA_COEFFICIENT},
    {"CKA_COLOR", CKA_COLOR},
    {"CKA_COPYABLE", CKA_COPYABLE},
    {"CKA_DECRYPT", CKA_DECRYPT},
    {"CKA_DEFAULT_CMS_ATTRIBUTES", CKA_DEFAULT_CMS_ATTRIBUTES},
    {"CKA_DERIVE", CKA_DERIVE},
    {"CKA_DERIVE_TEMPLATE", CKA_DERIVE_TEMPLATE},
    {"CKA_DESTROYABLE", CKA_DESTROYABLE},
    {"CKA_EC_PARAMS", CKA_EC_PARAMS},
    {"CKA_EC_POINT", CKA_EC_POINT},
    {"CKA_ENCODING_METHODS", CKA_ENCODING_METHODS},
    {"CKA_ENCRYPT", CKA_ENCRYPT},
    {"CKA_END_DATE", CKA_END_DATE},
    {"CKA_EXPONENT_1", CKA_EXPONENT_1},
    {"CKA_EXPONENT_2", CKA_EXPONENT_2},
    {"CKA_EXTRACTABLE", CKA_EXTRACTABLE},
    {"CKA_GOST28147_PARAMS", CKA_GOST28147_PARAMS},
    {"CKA_GOSTR3410_PARAMS", CKA_GOSTR3410_PARAMS},
    {"CKA_GOSTR3411_PARAMS", CKA_GOSTR3411_PARAMS},
    {"CKA_HASH_OF_ISSUER_PUBLIC_KEY", CKA_HASH_OF_ISSUER_PUBLIC_KEY},
    {"CKA_HASH_OF_SUBJECT_PUBLIC_KEY", CKA_HASH_OF_SUBJECT_PUBLIC_KEY},
    {"CKA_HAS_RESET", CKA_HAS_RESET},
    {"CKA_HW_FEATURE_TYPE", CKA_HW_FEATURE_TYPE},
    {"CKA_ID", CKA_ID},
    {"CKA_ISSUER", CKA_ISSUER},
    {"CKA_JAVA_MIDP_SECURITY_DOMAIN", CKA_JAVA_MIDP_SECURITY_DOMAIN},
    {"CKA_KEY_GEN_MECHANISM", CKA_KEY_GEN_MECHANISM},
    {"CKA_KEY_TYPE", CKA_KEY_TYPE},
    {"CKA_LABEL", CKA_LABEL},
    {"CKA_LOCAL", CKA_LOCAL},
    {"CKA_MECHANISM_TYPE", CKA_MECHANISM_TYPE},
    {"CKA_MIME_TYPES", CKA_MIME_TYPES},
    {"CKA_MODIFIABLE", CKA_MODIFIABLE},
    {"CKA_MODULUS", CKA_MODULUS},
    {"CKA_MODULUS_BITS", CKA_MODULUS_BITS},
    {"CKA_NAME_HASH_ALGORITHM", CKA_NAME_HASH_ALGORITHM},
    {"CKA_NEVER_EXTRACTABLE", CKA_NEVER_EXTRACTABLE},
    {"CKA_OBJECT_ID", CKA_OBJECT_ID},
    {"CKA_OTP_CHALLENGE_REQUIREMENT", CKA_OTP_CHALLENGE_REQUIREMENT},
    {"CKA_OTP_COUNTER", CKA_OTP_COUNTER},
    {"CKA_OTP_COUNTER_REQUIREMENT", CKA_OTP_COUNTER_REQUIREMENT},
    {"CKA_OTP_FORMAT", CKA_OTP_FORMAT},
    {"CKA_OTP_LENGTH", CKA_OTP_LENGTH},
    {"CKA_OTP_PIN_REQUIREMENT", CKA_OTP_PIN_REQUIREMENT},
    {"CKA_OTP_SERVICE_IDENTIFIER", CKA_OTP_SERVICE_IDENTIFIER},
    {"CKA_OTP_SERVICE_LOGO", CKA_OTP_SERVICE_LOGO},
    {"CKA_OTP_SERVICE_LOGO_TYPE", CKA_OTP_SERVICE_LOGO_TYPE},
    {"CKA_OTP_TIME", CKA_OTP_TIME},
    {"CKA_OTP_TIME_INTERVAL", CKA_OTP_TIME_INTERVAL},
    {"CKA_OTP_TIME_REQUIREMENT", CKA_OTP_TIME_REQUIREMENT},
    {"CKA_OTP_USER_FRIENDLY_MODE", CKA_OTP_USER_FRIENDLY_MODE},
    {"CKA_OTP_USER_IDENTIFIER", CKA_OTP_USER_IDENTIFIER},
    {"CKA_OWNER", CKA_OWNER},
    {"CKA_PIXEL_X", CKA_PIXEL_X},
    {"CKA_PIXEL_Y", CKA_PIXEL_Y},
    {"CKA_PRIME", CKA_PRIME},
    {"CKA_PRIME_1", CKA_PRIME_1},
    {"CKA_PRIME_2", CKA_PRIME_2},
    {"CKA_PRIME_BITS", CKA_PRIME_BITS},
    {"CKA_PRIVATE", CKA_PRIVATE},
    {"CKA_PRIVATE_EXPONENT", CKA_PRIVATE_EXPONENT},
    {"CKA_PROFILE_ID", CKA_PROFILE_ID},
    {"CKA_PUBLIC_EXPONENT", CKA_PUBLIC_EXPONENT},
    {"CKA_PUBLIC_KEY_INFO", CKA_PUBLIC_KEY_INFO},
    {"CKA_REQUIRED_CMS_ATTRIBUTES", CKA_REQUIRED_CMS_ATTRIBUTES},
    {"CKA_RESET_ON_INIT", CKA_RESET_ON_INIT},
    {"CKA_RESOLUTION", CKA_RESOLUTION},
    {"CKA_SENSITIVE", CKA_SENSITIVE},
    {"CKA_SERIAL_NUMBER", CKA_SERIAL_NUMBER},
    {"CKA_SIGN", CKA_SIGN},
    {"CKA_SIGN_RECOVER", CKA_SIGN_RECOVER},
    {"CKA_START_DATE", CKA_START_DATE},
    {"CKA_SUBJECT", CKA_SUBJECT},
    {"CKA_SUBPRIME", CKA_SUBPRIME},
    {"CKA_SUB_PRIME_BITS", CKA_SUB_PRIME_BITS},
    {"CKA_SUPPORTED_CMS_ATTRIBUTES", CKA_SUPPORTED_CMS_ATTRIBUTES},
    {"CKA_TOKEN", CKA_TOKEN},
    {"CKA_TRUSTED", CKA_TRUSTED},
    {"CKA_UNWRAP", CKA_UNWRAP},
    {"CKA_UNWRAP_TEMPLATE", CKA_UNWRAP_TEMPLATE},
    {"CKA_URL", CKA_URL},
    {"CKA_VALUE", CKA_VALUE},
    {"CKA_VALUE_BITS", CKA_VALUE_BITS},
    {"CKA_VALUE_LEN", CKA_VALUE_LEN},
    {"CKA_VENDOR_DEFINED", CKA_VENDOR_DEFINED},
    {"CKA_VERIFY", CKA_VERIFY},
    {"CKA_VERIFY_RECOVER", CKA_VERIFY_RECOVER},
    {"CKA_WRAP", CKA_WRAP},
    {"CKA_WRAP_TEMPLATE", CKA_WRAP_TEMPLATE},
    {"CKA_WRAP_WITH_TRUSTED", CKA_WRAP_WITH_TRUSTED},
    {"CKC_OPENPGP", CKC_OPENPGP},
    {"CKC_VENDOR_DEFINED", CKC_VENDOR_DEFINED},
    {"CKC_WTLS", CKC_WTLS},
    {"CKC_X_509", CKC_X_509},
    {"CKC_X_509_ATTR_CERT", CKC_X_509_ATTR_CERT},
    {"CKD_CPDIVERSIFY_KDF", CKD_CPDIVERSIFY_KDF},
    {"CKD_NULL", CKD_NULL},
    {"CKD_SHA1_KDF", CKD_SHA1_KDF},
    {"CKD_SHA1_KDF_ASN1", CKD_SHA1_KDF_ASN1},
    {"CKD_SHA1_KDF_CONCATENATE", CKD_SHA1_KDF_CONCATENATE},
    {"CKD_SHA224_KDF", CKD_SHA224_KDF},
    {"CKD_SHA256_KDF", CKD_SHA256_KDF},
    {"CKD_SHA384_KDF", CKD_SHA384_KDF},
    {"CKD_SHA512_KDF", CKD_SHA512_KDF},
    {"CKF_ARRAY_ATTRIBUTE", CKF_ARRAY_ATTRIBUTE},
    {"CKF_CLOCK_ON_TOKEN", CKF_CLOCK_ON_TOKEN},
    {"CKF_DECRYPT", CKF_DECRYPT},
    {"CKF_DERIVE", CKF_DERIVE},
    {"CKF_DIGEST", CKF_DIGEST},
    {"CKF_DONT_BLOCK", CKF_DONT_BLOCK},
    {"CKF_DUAL_CRYPTO_OPERATIONS", CKF_DUAL_CRYPTO_OPERATIONS},
    {"CKF_EC_COMPRESS", CKF_EC_COMPRESS},
    {"CKF_EC_F_P", CKF_EC_F_P},
    {"CKF_EC_NAMEDCURVE", CKF_EC_NAMEDCURVE},
    {"CKF_EC_UNCOMPRESS", CKF_EC_UNCOMPRESS},
    {"CKF_ENCRYPT", CKF_ENCRYPT},
    {"CKF_END_OF_MESSAGE", CKF_END_OF_MESSAGE},
    {"CKF_EXCLUDE_CHALLENGE", CKF_EXCLUDE_CHALLENGE},
    {"CKF_EXCLUDE_COUNTER", CKF_EXCLUDE_COUNTER},
    {"CKF_EXCLUDE_PIN", CKF_EXCLUDE_PIN},
    {"CKF_EXCLUDE_TIME", CKF_EXCLUDE_TIME},
    {"CKF_EXTENSION", CKF_EXTENSION},
    {"CKF_FIND_OBJECTS", CKF_FIND_OBJECTS},
    {"CKF_GENERATE", CKF_GENERATE},
    {"CKF_GENERATE_KEY_PAIR", CKF_GENERATE_KEY_PAIR},
    {"CKF_HW", CKF_HW},
    {"CKF_HW_SLOT", CKF_HW_SLOT},
    {"CKF_INTERFACE_FORK_SAFE", CKF_INTERFACE_FORK_SAFE},
    {"CKF_LIBRARY_CANT_CREATE_OS_THREADS", CKF_LIBRARY_CANT_CREATE_OS_THREADS},
    {"CKF_LOGIN_REQUIRED", CKF_LOGIN_REQUIRED},
    {"CKF_MESSAGE_DECRYPT", CKF_MESSAGE_DECRYPT},
    {"CKF_MESSAGE_ENCRYPT", CKF_MESSAGE_ENCRYPT},
    {"CKF_MESSAGE_SIGN", CKF_MESSAGE_SIGN},
    {"CKF_MESSAGE_VERIFY", CKF_MESSAGE_VERIFY},
    {"CKF_MULTI_MESSAGE", CKF_MULTI_MESSAGE},
    {"CKF_NEXT_OTP", CKF_NEXT_OTP},
    {"CKF_OS_LOCKING_OK", CKF_OS_LOCKING_OK},
    {"CKF_PROTECTED_AUTHENTICATION_PATH", CKF_PROTECTED_AUTHENTICATION_PATH},
    {"CKF_REMOVABLE_DEVICE", CKF_REMOVABLE_DEVICE},
    {"CKF_RESTORE_KEY_NOT_NEEDED", CKF_RESTORE_KEY_NOT_NEEDED},
    {"CKF_RNG", CKF_RNG},
    {"CKF_RW_SESSION", CKF_RW_SESSION},
    {"CKF_SERIAL_SESSION", CKF_SERIAL_SESSION},
    {"CKF_SIGN", CKF_SIGN},
    {"CKF_SIGN_RECOVER", CKF_SIGN_RECOVER},
    {"CKF_SO_PIN_COUNT_LOW", CKF_SO_PIN_COUNT_LOW},
    {"CKF_SO_PIN_FINAL_TRY", CKF_SO_PIN_FINAL_TRY},
    {"CKF_SO_PIN_LOCKED", CKF_SO_PIN_LOCKED},
    {"CKF_SO_PIN_TO_BE_CHANGED", CKF_SO_PIN_TO_BE_CHANGED},
    {"CKF_TOKEN_INITIALIZED", CKF_TOKEN_INITIALIZED},
    {"CKF_TOKEN_PRESENT", CKF_TOKEN_PRESENT},
    {"CKF_UNWRAP", CKF_UNWRAP},
    {"CKF_USER_FRIENDLY_OTP", CKF_USER_FRIENDLY_OTP},
    {"CKF_USER_PIN_COUNT_LOW", CKF_USER_PIN_COUNT_LOW},
    {"CKF_USER_PIN_FINAL_TRY", CKF_USER_PIN_FINAL_TRY},
    {"CKF_USER_PIN_INITIALIZED", CKF_USER_PIN_INITIALIZED},
    {"CKF_USER_PIN_LOCKED", CKF_USER_PIN_LOCKED},
    {"CKF_USER_PIN_TO_BE_CHANGED", CKF_USER_PIN_TO_BE_CHANGED},
    {"CKF_VERIFY", CKF_VERIFY},
    {"CKF_VERIFY_RECOVER", CKF_VERIFY_RECOVER},
    {"CKF_WRAP", CKF_WRAP},
    {"CKF_WRITE_PROTECTED", CKF_WRITE_PROTECTED},
    {"CKG_MGF1_SHA1", CKG_MGF1_SHA1},
    {"CKG_MGF1_SHA224", CKG_MGF1_SHA224},
    {"CKG_MGF1_SHA256", CKG_MGF1_SHA256},
    {"CKG_MGF1_SHA384", CKG_MGF1_SHA384},
    {"CKG_MGF1_SHA512", CKG_MGF1_SHA512},
    {"CKH_CLOCK", CKH_CLOCK},
    {"CKH_MONOTONIC_COUNTER", CKH_MONOTONIC_COUNTER},
    {"CKH_USER_INTERFACE", CKH_USER_INTERFACE},
    {"CKH_VENDOR_DEFINED", CKH_VENDOR_DEFINED},
    {"CKK_ACTI", CKK_ACTI},
    {"CKK_AES", CKK_AES},
    {"CKK_ARIA", CKK_ARIA},
    {"CKK_BATON", CKK_BATON},
    {"CKK_BLOWFISH", CKK_BLOWFISH},
    {"CKK_CAMELLIA", CKK_CAMELLIA},
    {"CKK_CAST", CKK_CAST},
    {"CKK_CAST128", CKK_CAST128},
    {"CKK_CAST3", CKK_CAST3},
    {"CKK_CDMF", CKK_CDMF},
    {"CKK_CHACHA20", CKK_CHACHA20},
    {"CKK_DES", CKK_DES},
    {"CKK_DES2", CKK_DES2},
    {"CKK_DES3", CKK_DES3},
    {"CKK_DH", CKK_DH},
    {"CKK_DSA", CKK_DSA},
    {"CKK_EC", CKK_EC},
    {"CKK_ECDSA", CKK_ECDSA},
    {"CKK_EC_EDWARDS", CKK_EC_EDWARDS},
    {"CKK_EC_MONTGOMERY", CKK_EC_MONTGOMERY},
    {"CKK_GENERIC_SECRET", CKK_GENERIC_SECRET},
    {"CKK_GOST28147", CKK_GOST28147},
    {"CKK_GOSTR3410", CKK_GOSTR3410},
    {"CKK_GOSTR3411", CKK_GOSTR3411},
    {"CKK_HOTP", CKK_HOTP},
    {"CKK_IDEA", CKK_IDEA},
    {"CKK_JUNIPER", CKK_JUNIPER},
    {"CKK_KEA", CKK_KEA},
    {"CKK_MD5_HMAC", CKK_MD5_HMAC},
    {"CKK_POLY1305", CKK_POLY1305},
    {"CKK_RC2", CKK_RC2},
    {"CKK_RC4", CKK_RC4},
    {"CKK_RC5", CKK_RC5},
    {"CKK_RIPEMD128_HMAC", CKK_RIPEMD128_HMAC},
    {"CKK_RIPEMD160_HMAC", CKK_RIPEMD160_HMAC},
    {"CKK_RSA", CKK_RSA},
    {"CKK_SALSA20", CKK_SALSA20},
    {"CKK_SECURID", CKK_SECURID},
    {"CKK_SEED", CKK_SEED},
    {"CKK_SHA224_HMAC", CKK_SHA224_HMAC},
    {"CKK_SHA256_HMAC", CKK_SHA256_HMAC},
    {"CKK_SHA384_HMAC", CKK_SHA384_HMAC},
    {"CKK_SHA512_HMAC", CKK_SHA512_HMAC},
    {"CKK_SHA_1_HMAC", CKK_SHA_1_HMAC},
    {"CKK_SKIPJACK", CKK_SKIPJACK},
    {"CKK_TWOFISH", CKK_TWOFISH},
    {"CKK_VENDOR_DEFINED", CKK_VENDOR_DEFINED},
    {"CKK_X9_42_DH", CKK_X9_42_DH},
    {"CKM_ACTI", CKM_ACTI},
    {"CKM_ACTI_KEY_GEN", CKM_ACTI_KEY_GEN},
    {"CKM_AES_CBC", CKM_AES_CBC},
    {"CKM_AES_CBC_ENCRYPT_DATA", CKM_AES_CBC_ENCRYPT_DATA},
    {"CKM_AES_CBC_PAD", CKM_AES_CBC_PAD},
    {"CKM_AES_CCM", CKM_AES_CCM},
    {"CKM_AES_CFB1", CKM_AES_CFB1},
    {"CKM_AES_CFB128", CKM_AES_CFB128},
    {"CKM_AES_CFB64", CKM_AES_CFB64},
    {"CKM_AES_CFB8", CKM_AES_CFB8},
    {"CKM_AES_CMAC", CKM_AES_CMAC},
    {"CKM_AES_CMAC_GENERAL", CKM_AES_CMAC_GENERAL},
    {"CKM_AES_CTR", CKM_AES_CTR},
    {"CKM_AES_CTS", CKM_AES_CTS},
    {"CKM_AES_ECB", CKM_AES_ECB},
    {"CKM_AES_ECB_ENCRYPT_DATA", CKM_AES_ECB_ENCRYPT_DATA},
    {"CKM_AES_GCM", CKM_AES_GCM},
    {"CKM_AES_GMAC", CKM_AES_GMAC},
    {"CKM_AES_KEY_GEN", CKM_AES_KEY_GEN},
    {"CKM_AES_KEY_WRAP", CKM_AES_KEY_WRAP},
    {"CKM_AES_KEY_WRAP_PAD", CKM_AES_KEY_WRAP_PAD},
    {"CKM_AES_MAC", CKM_AES_MAC},
    {"CKM_AES_MAC_GENERAL", CKM_AES_MAC_GENERAL},
    {"CKM_AES_OFB", CKM_AES_OFB},
    {"CKM_AES_XCBC_MAC", CKM_AES_XCBC_MAC},
    {"CKM_AES_XCBC_MAC_96", CKM_AES_XCBC_MAC_96},
    {"CKM_ARIA_CBC", CKM_ARIA_CBC},
    {"CKM_ARIA_CBC_ENCRYPT_DATA", CKM_ARIA_CBC_ENCRYPT_DATA},
    {"CKM_ARIA_CBC_PAD", CKM_ARIA_CBC_PAD},
    {"CKM_ARIA_ECB", CKM_ARIA_ECB},
    {"CKM_ARIA_ECB_ENCRYPT_DATA", CKM_ARIA_ECB_ENCRYPT_DATA},
    {"CKM_ARIA_KEY_GEN", CKM_ARIA_KEY_GEN},
    {"CKM_ARIA_MAC", CKM_ARIA_MAC},
    {"CKM_ARIA_MAC_GENERAL", CKM_ARIA_MAC_GENERAL},
    {"CKM_BATON_CBC128", CKM_BATON_CBC128},
    {"CKM_BATON_COUNTER", CKM_BATON_COUNTER},
    {"CKM_BATON_ECB128", CKM_BATON_ECB128},
    {"CKM_BATON_ECB96", CKM_BATON_ECB96},
    {"CKM_BATON_KEY_GEN", CKM_BATON_KEY_GEN},
    {"CKM_BATON_SHUFFLE", CKM_BATON_SHUFFLE},
    {"CKM_BATON_WRAP", CKM_BATON_WRAP},
    {"CKM_BLOWFISH_CBC", CKM_BLOWFISH_CBC},
    {"CKM_BLOWFISH_CBC_PAD", CKM_BLOWFISH_CBC_PAD},
    {"CKM_BLOWFISH_KEY_GEN", CKM_BLOWFISH_KEY_GEN},
    {"CKM_CAMELLIA_CBC", CKM_CAMELLIA_CBC},
    {"CKM_CAMELLIA_CBC_ENCRYPT_DATA", CKM_CAMELLIA_CBC_ENCRYPT_DATA},
    {"CKM_CAMELLIA_CBC_PAD", CKM_CAMELLIA_CBC_PAD},
    {"CKM_CAMELLIA_CTR", CKM_CAMELLIA_CTR},
    {"CKM_CAMELLIA_ECB", CKM_CAMELLIA_ECB},
    {"CKM_CAMELLIA_ECB_ENCRYPT_DATA", CKM_CAMELLIA_ECB_ENCRYPT_DATA},
    {"CKM_CAMELLIA_KEY_GEN", CKM_CAMELLIA_KEY_GEN},
    {"CKM_CAMELLIA_MAC", CKM_CAMELLIA_MAC},
    {"CKM_CAMELLIA_MAC_GENERAL", CKM_CAMELLIA_MAC_GENERAL},
    {"CKM_CAST128_CBC", CKM_CAST128_CBC},
    {"CKM_CAST128_CBC_PAD", CKM_CAST128_CBC_PAD},
    {"CKM_CAST128_ECB", CKM_CAST128_ECB},
    {"CKM_CAST128_KEY_GEN", CKM_CAST128_KEY_GEN},
    {"CKM_CAST128_MAC", CKM_CAST128_MAC},
    {"CKM_CAST128_MAC_GENERAL", CKM_CAST128_MAC_GENERAL},
    {"CKM_CAST3_CBC", CKM_CAST3_CBC},
    {"CKM_CAST3_CBC_PAD", CKM_CAST3_CBC_PAD},
    {"CKM_CAST3_ECB", CKM_CAST3_ECB},
    {"CKM_CAST3_KEY_GEN", CKM_CAST3_KEY_GEN},
    {"CKM_CAST3_MAC", CKM_CAST3_MAC},
    {"CKM_CAST3_MAC_GENERAL", CKM_CAST3_MAC_GENERAL},
    {"CKM_CAST5_CBC", CKM_CAST5_CBC},
    {"CKM_CAST5_CBC_PAD", CKM_CAST5_CBC_PAD},
    {"CKM_CAST5_ECB", CKM_CAST5_ECB},
    {"CKM_CAST5_KEY_GEN", CKM_CAST5_KEY_GEN},
    {"CKM_CAST5_MAC", CKM_CAST5_MAC},
    {"CKM_CAST5_MAC_GENERAL", CKM_CAST5_MAC_GENERAL},
    {"CKM_CAST_CBC", CKM_CAST_CBC},
    {"CKM_CAST_CBC_PAD", CKM_CAST_CBC_PAD},
    {"CKM_CAST_ECB", CKM_CAST_ECB},
    {"CKM_CAST_KEY_GEN", CKM_CAST_KEY_GEN},
    {"CKM_CAST_MAC", CKM_CAST_MAC},
    {"CKM_CAST_MAC_GENERAL", CKM_CAST_MAC_GENERAL},
    {"CKM_CDMF_CBC", CKM_CDMF_CBC},
    {"CKM_CDMF_CBC_PAD", CKM_CDMF_CBC_PAD},
    {"CKM_CDMF_ECB", CKM_CDMF_ECB},
    {"CKM_CDMF_KEY_GEN", CKM_CDMF_KEY_GEN},
    {"CKM_CDMF_MAC", CKM_CDMF_MAC},
    {"CKM_CDMF_MAC_GENERAL", CKM_CDMF_MAC_GENERAL},
    {"CKM_CHACHA20", CKM_CHACHA20},
    {"CKM_CHACHA20_KEY_GEN", CKM_CHACHA20_KEY_GEN},
    {"CKM_CMS_SIG", CKM_CMS_SIG},
    {"CKM_CONCATENATE_BASE_AND_DATA", CKM_CONCATENATE_BASE_AND_DATA},
    {"CKM_CONCATENATE_BASE_AND_KEY", CKM_CONCATENATE_BASE_AND_KEY},
    {"CKM_CONCATENATE_DATA_AND_BASE", CKM_CONCATENATE_DATA_AND_BASE},
    {"CKM_DES2_KEY_GEN", CKM_DES2_KEY_GEN},
    {"CKM_DES3_CBC", CKM_DES3_CBC},
    {"CKM_DES3_CBC_ENCRYPT_DATA", CKM_DES3_CBC_ENCRYPT_DATA},
    {"CKM_DES3_CBC_PAD", CKM_DES3_CBC_PAD},
    {"CKM_DES3_CMAC", CKM_DES3_CMAC},
    {"CKM_DES3_CMAC_GENERAL", CKM_DES3_CMAC_GENERAL},
    {"CKM_DES3_ECB", CKM_DES3_ECB},
    {"CKM_DES3_ECB_ENCRYPT_DATA", CKM_DES3_ECB_ENCRYPT_DATA},
    {"CKM_DES3_KEY_GEN", CKM_DES3_KEY_GEN},
    {"CKM_DES3_MAC", CKM_DES3_MAC},
    {"CKM_DES3_MAC_GENERAL", CKM_DES3_MAC_GENERAL},
    {"CKM_DES_CBC", CKM_DES_CBC},
    {"CKM_DES_CBC_ENCRYPT_DATA", CKM_DES_CBC_ENCRYPT_DATA},
    {"CKM_DES_CBC_PAD", CKM_DES_CBC_PAD},
    {"CKM_DES_CFB64", CKM_DES_CFB64},
    {"CKM_DES_CFB8", CKM_DES_CFB8},
    {"CKM_DES_ECB", CKM_DES_ECB},
    {"CKM_DES_ECB_ENCRYPT_DATA", CKM_DES_ECB_ENCRYPT_DATA},
    {"CKM_DES_KEY_GEN", CKM_DES_KEY_GEN},
    {"CKM_DES_MAC", CKM_DES_MAC},
    {"CKM_DES_MAC_GENERAL", CKM_DES_MAC_GENERAL},
    {"CKM_DES_OFB64", CKM_DES_OFB64},
    {"CKM_DES_OFB8", CKM_DES_OFB8},
    {"CKM_DH_PKCS_DERIVE", CKM_DH_PKCS_DERIVE},
    {"CKM_DH_PKCS_KEY_PAIR_GEN", CKM_DH_PKCS_KEY_PAIR_GEN},
    {"CKM_DH_PKCS_PARAMETER_GEN", CKM_DH_PKCS_PARAMETER_GEN},
    {"CKM_DSA", CKM_DSA},
    {"CKM_DSA_KEY_PAIR_GEN", CKM_DSA_KEY_PAIR_GEN},
    {"CKM_DSA_PARAMETER_GEN", CKM_DSA_PARAMETER_GEN},
    {"CKM_DSA_PROBABLISTIC_PARAMETER_GEN", CKM_DSA_PROBABLISTIC_PARAMETER_GEN},
    {"CKM_DSA_SHA1", CKM_DSA_SHA1},
    {"CKM_DSA_SHA224", CKM_DSA_SHA224},
    {"CKM_DSA_SHA256", CKM_DSA_SHA256},
    {"CKM_DSA_SHA384", CKM_DSA_SHA384},
    {"CKM_DSA_SHA512", CKM_DSA_SHA512},
    {"CKM_DSA_SHAWE_TAYLOR_PARAMETER_GEN", CKM_DSA_SHAWE_TAYLOR_PARAMETER_GEN},
    {"CKM_ECDH1_COFACTOR_DERIVE", CKM_ECDH1_COFACTOR_DERIVE},
    {"CKM_ECDH1_DERIVE", CKM_ECDH1_DERIVE},
    {"CKM_ECDH_AES_KEY_WRAP", CKM_ECDH_AES_KEY_WRAP},
    {"CKM_ECDSA", CKM_ECDSA},
    {"CKM_ECDSA_KEY_PAIR_GEN", CKM_ECDSA_KEY_PAIR_GEN},
    {"CKM_ECDSA_SHA1", CKM_ECDSA_SHA1},
    {"CKM_ECDSA_SHA224", CKM_ECDSA_SHA224},
    {"CKM_ECDSA_SHA256", CKM_ECDSA_SHA256},
    {"CKM_ECDSA_SHA384", CKM_ECDSA_SHA384},
    {"CKM_ECDSA_SHA512", CKM_ECDSA_SHA512},
    {"CKM_ECMQV_DERIVE", CKM_ECMQV_DERIVE},
    {"CKM_EC_EDWARDS_KEY_PAIR_GEN", CKM_EC_EDWARDS_KEY_PAIR_GEN},
    {"CKM_EC_KEY_PAIR_GEN", CKM_EC_KEY_PAIR_GEN},
    {"CKM_EC_MONTGOMERY_KEY_PAIR_GEN", CKM_EC_MONTGOMERY_KEY_PAIR_GEN},
    {"CKM_EDDSA", CKM_EDDSA},
    {"CKM_EXTRACT_KEY_FROM_KEY", CKM_EXTRACT_KEY_FROM_KEY},
    {"CKM_FASTHASH", CKM_FASTHASH},
    {"CKM_FORTEZZA_TIMESTAMP", CKM_FORTEZZA_TIMESTAMP},
    {"CKM_GENERIC_SECRET_KEY_GEN", CKM_GENERIC_SECRET_KEY_GEN},
    {"CKM_GOST28147", CKM_GOST28147},
    {"CKM_GOST28147_ECB", CKM_GOST28147_ECB},
    {"CKM_GOST28147_KEY_GEN", CKM_GOST28147_KEY_GEN},
    {"CKM_GOST28147_KEY_WRAP", CKM_GOST28147_KEY_WRAP},
    {"CKM_GOST28147_MAC", CKM_GOST28147_MAC},
    {"CKM_GOSTR3410", CKM_GOSTR3410},
    {"CKM_GOSTR3410_DERIVE", CKM_GOSTR3410_DERIVE},
    {"CKM_GOSTR3410_KEY_PAIR_GEN", CKM_GOSTR3410_KEY_PAIR_GEN},
    {"CKM_GOSTR3410_KEY_WRAP", CKM_GOSTR3410_KEY_WRAP},
    {"CKM_GOSTR3410_WITH_GOSTR3411", CKM_GOSTR3410_WITH_GOSTR3411},
    {"CKM_GOSTR3411", CKM_GOSTR3411},
    {"CKM_GOSTR3411_HMAC", CKM_GOSTR3411_HMAC},
    {"CKM_HOTP", CKM_HOTP},
    {"CKM_HOTP_KEY_GEN", CKM_HOTP_KEY_GEN},
    {"CKM_IDEA_CBC", CKM_IDEA_CBC},
    {"CKM_IDEA_CBC_PAD", CKM_IDEA_CBC_PAD},
    {"CKM_IDEA_ECB", CKM_IDEA_ECB},
    {"CKM_IDEA_KEY_GEN", CKM_IDEA_KEY_GEN},
    {"CKM_IDEA_MAC", CKM_IDEA_MAC},
    {"CKM_IDEA_MAC_GENERAL", CKM_IDEA_MAC_GENERAL},
    {"CKM_JUNIPER_CBC128", CKM_JUNIPER_CBC128},
    {"CKM_JUNIPER_COUNTER", CKM_JUNIPER_COUNTER},
    {"CKM_JUNIPER_ECB128", CKM_JUNIPER_ECB128},
    {"CKM_JUNIPER_KEY_GEN", CKM_JUNIPER_KEY_GEN},
    {"CKM_JUNIPER_SHUFFLE", CKM_JUNIPER_SHUFFLE},
    {"CKM_JUNIPER_WRAP", CKM_JUNIPER_WRAP},
    {"CKM_KEA_KEY_DERIVE", CKM_KEA_KEY_DERIVE},
    {"CKM_KEA_KEY_PAIR_GEN", CKM_KEA_KEY_PAIR_GEN},
    {"CKM_KEY_WRAP_LYNKS", CKM_KEY_WRAP_LYNKS},
    {"CKM_KEY_WRAP_SET_OAEP", CKM_KEY_WRAP_SET_OAEP},
    {"CKM_KIP_DERIVE", CKM_KIP_DERIVE},
    {"CKM_KIP_MAC", CKM_KIP_MAC},
    {"CKM_KIP_WRAP", CKM_KIP_WRAP},
    {"CKM_MD2", CKM_MD2},
    {"CKM_MD2_HMAC", CKM_MD2_HMAC},
    {"CKM_MD2_HMAC_GENERAL", CKM_MD2_HMAC_GENERAL},
    {"CKM_MD2_KEY_DERIVATION", CKM_MD2_KEY_DERIVATION},
    {"CKM_MD2_RSA_PKCS", CKM_MD2_RSA_PKCS},
    {"CKM_MD5", CKM_MD5},
    {"CKM_MD5_HMAC", CKM_MD5_HMAC},
    {"CKM_MD5_HMAC_GENERAL", CKM_MD5_HMAC_GENERAL},
    {"CKM_MD5_KEY_DERIVATION", CKM_MD5_KEY_DERIVATION},
    {"CKM_MD5_RSA_PKCS", CKM_MD5_RSA_PKCS},
    {"CKM_PBA_SHA1_WITH_SHA1_HMAC", CKM_PBA_SHA1_WITH_SHA1_HMAC},
    {"CKM_PBE_MD2_DES_CBC", CKM_PBE_MD2_DES_CBC},
    {"CKM_PBE_MD5_CAST128_CBC", CKM_PBE_MD5_CAST128_CBC},
    {"CKM_PBE_MD5_CAST3_CBC", CKM_PBE_MD5_CAST3_CBC},
    {"CKM_PBE_MD5_CAST5_CBC", CKM_PBE_MD5_CAST5_CBC},
    {"CKM_PBE_MD5_CAST_CBC", CKM_PBE_MD5_CAST_CBC},
    {"CKM_PBE_MD5_DES_CBC", CKM_PBE_MD5_DES_CBC},
    {"CKM_PBE_SHA1_CAST128_CBC", CKM_PBE_SHA1_CAST128_CBC},
    {"CKM_PBE_SHA1_CAST5_CBC", CKM_PBE_SHA1_CAST5_CBC},
    {"CKM_PBE_SHA1_DES2_EDE_CBC", CKM_PBE_SHA1_DES2_EDE_CBC},
    {"CKM_PBE_SHA1_DES3_EDE_CBC", CKM_PBE_SHA1_DES3_EDE_CBC},
    {"CKM_PBE_SHA1_RC2_128_CBC", CKM_PBE_SHA1_RC2_128_CBC},
    {"CKM_PBE_SHA1_RC2_40_CBC", CKM_PBE_SHA1_RC2_40_CBC},
    {"CKM_PBE_SHA1_RC4_128", CKM_PBE_SHA1_RC4_128},
    {"CKM_PBE_SHA1_RC4_40", CKM_PBE_SHA1_RC4_40},
    {"CKM_PKCS5_PBKD2", CKM_PKCS5_PBKD2},
    {"CKM_POLY1305", CKM_POLY1305},
    {"CKM_POLY1305_KEY_GEN", CKM_POLY1305_KEY_GEN},
    {"CKM_RC2_CBC", CKM_RC2_CBC},
    {"CKM_RC2_CBC_PAD", CKM_RC2_CBC_PAD},
    {"CKM_RC2_ECB", CKM_RC2_ECB},
    {"CKM_RC2_KEY_GEN", CKM_RC2_KEY_GEN},
    {"CKM_RC2_MAC", CKM_RC2_MAC},
    {"CKM_RC2_MAC_GENERAL", CKM_RC2_MAC_GENERAL},
    {"CKM_RC4", CKM_RC4},
    {"CKM_RC4_KEY_GEN", CKM_RC4_KEY_GEN},
    {"CKM_RC5_CBC", CKM_RC5_CBC},
    {"CKM_RC5_CBC_PAD", CKM_RC5_CBC_PAD},
    {"CKM_RC5_ECB", CKM_RC5_ECB},
    {"CKM_RC5_KEY_GEN", CKM_RC5_KEY_GEN},
    {"CKM_RC5_MAC", CKM_RC5_MAC},
    {"CKM_RC5_MAC_GENERAL", CKM_RC5_MAC_GENERAL},
    {"CKM_RIPEMD128", CKM_RIPEMD128},
    {"CKM_RIPEMD128_HMAC", CKM_RIPEMD128_HMAC},
    {"CKM_RIPEMD128_HMAC_GENERAL", CKM_RIPEMD128_HMAC_GENERAL},
    {"CKM_RIPEMD128_RSA_PKCS", CKM_RIPEMD128_RSA_PKCS},
    {"CKM_RIPEMD160", CKM_RIPEMD160},
    {"CKM_RIPEMD160_HMAC", CKM_RIPEMD160_HMAC},
    {"CKM_RIPEMD160_HMAC_GENERAL", CKM_RIPEMD160_HMAC_GENERAL},
    {"CKM_RIPEMD160_RSA_PKCS", CKM_RIPEMD160_RSA_PKCS},
    {"CKM_RSA_9796", CKM_RSA_9796},
    {"CKM_RSA_AES_KEY_WRAP", CKM_RSA_AES_KEY_WRAP},
    {"CKM_RSA_PKCS", CKM_RSA_PKCS},
    {"CKM_RSA_PKCS_KEY_PAIR_GEN", CKM_RSA_PKCS_KEY_PAIR_GEN},
    {"CKM_RSA_PKCS_OAEP", CKM_RSA_PKCS_OAEP},
    {"CKM_RSA_PKCS_OAEP_TPM_1_1", CKM_RSA_PKCS_OAEP_TPM_1_1},
    {"CKM_RSA_PKCS_PSS", CKM_RSA_PKCS_PSS},
    {"CKM_RSA_PKCS_TPM_1_1", CKM_RSA_PKCS_TPM_1_1},
    {"CKM_RSA_X9_31", CKM_RSA_X9_31},
    {"CKM_RSA_X9_31_KEY_PAIR_GEN", CKM_RSA_X9_31_KEY_PAIR_GEN},
    {"CKM_RSA_X_509", CKM_RSA_X_509},
    {"CKM_SECURID", CKM_SECURID},
    {"CKM_SECURID_KEY_GEN", CKM_SECURID_KEY_GEN},
    {"CKM_SEED_CBC", CKM_SEED_CBC},
    {"CKM_SEED_CBC_ENCRYPT_DATA", CKM_SEED_CBC_ENCRYPT_DATA},
    {"CKM_SEED_CBC_PAD", CKM_SEED_CBC_PAD},
    {"CKM_SEED_ECB", CKM_SEED_ECB},
    {"CKM_SEED_ECB_ENCRYPT_DATA", CKM_SEED_ECB_ENCRYPT_DATA},
    {"CKM_SEED_KEY_GEN", CKM_SEED_KEY_GEN},
    {"CKM_SEED_MAC", CKM_SEED_MAC},
    {"CKM_SEED_MAC_GENERAL", CKM_SEED_MAC_GENERAL},
    {"CKM_SHA1_KEY_DERIVATION", CKM_SHA1_KEY_DERIVATION},
    {"CKM_SHA1_RSA_PKCS", CKM_SHA1_RSA_PKCS},
    {"CKM_SHA1_RSA_PKCS_PSS", CKM_SHA1_RSA_PKCS_PSS},
    {"CKM_SHA1_RSA_X9_31", CKM_SHA1_RSA_X9_31},
    {"CKM_SHA224", CKM_SHA224},
    {"CKM_SHA224_HMAC", CKM_SHA224_HMAC},
    {"CKM_SHA224_HMAC_GENERAL", CKM_SHA224_HMAC_GENERAL},
    {"CKM_SHA224_KEY_DERIVATION", CKM_SHA224_KEY_DERIVATION},
    {"CKM_SHA224_RSA_PKCS", CKM_SHA224_RSA_PKCS},
    {"CKM_SHA224_RSA_PKCS_PSS", CKM_SHA224_RSA_PKCS_PSS},
    {"CKM_SHA256", CKM_SHA256},
    {"CKM_SHA256_HMAC", CKM_SHA256_HMAC},
    {"CKM_SHA256_HMAC_GENERAL", CKM_SHA256_HMAC_GENERAL},
    {"CKM_SHA256_KEY_DERIVATION", CKM_SHA256_KEY_DERIVATION},
    {"CKM_SHA256_RSA_PKCS", CKM_SHA256_RSA_PKCS},
    {"CKM_SHA256_RSA_PKCS_PSS", CKM_SHA256_RSA_PKCS_PSS},
    {"CKM_SHA384", CKM_SHA384},
    {"CKM_SHA384_HMAC", CKM_SHA384_HMAC},
    {"CKM_SHA384_HMAC_GENERAL", CKM_SHA384_HMAC_GENERAL},
    {"CKM_SHA384_KEY_DERIVATION", CKM_SHA384_KEY_DERIVATION},
    {"CKM_SHA384_RSA_PKCS", CKM_SHA384_RSA_PKCS},
    {"CKM_SHA384_RSA_PKCS_PSS", CKM_SHA384_RSA_PKCS_PSS},
    {"CKM_SHA512", CKM_SHA512},
    {"CKM_SHA512_224", CKM_SHA512_224},
    {"CKM_SHA512_224_HMAC", CKM_SHA512_224_HMAC},
    {"CKM_SHA512_224_HMAC_GENERAL", CKM_SHA512_224_HMAC_GENERAL},
    {"CKM_SHA512_224_KEY_DERIVATION", CKM_SHA512_224_KEY_DERIVATION},
    {"CKM_SHA512_256", CKM_SHA512_256},
    {"CKM_SHA512_256_HMAC", CKM_SHA512_256_HMAC},
    {"CKM_SHA512_256_HMAC_GENERAL", CKM_SHA512_256_HMAC_GENERAL},
    {"CKM_SHA512_256_KEY_DERIVATION", CKM_SHA512_256_KEY_DERIVATION},
    {"CKM_SHA512_HMAC", CKM_SHA512_HMAC},
    {"CKM_SHA512_HMAC_GENERAL", CKM_SHA512_HMAC_GENERAL},
    {"CKM_SHA512_KEY_DERIVATION", CKM_SHA512_KEY_DERIVATION},
    {"CKM_SHA512_RSA_PKCS", CKM_SHA512_RSA_PKCS},
    {"CKM_SHA512_RSA_PKCS_PSS", CKM_SHA512_RSA_PKCS_PSS},
    {"CKM_SHA512_T", CKM_SHA512_T},
    {"CKM_SHA512_T_HMAC", CKM_SHA512_T_HMAC},
    {"CKM_SHA512_T_HMAC_GENERAL", CKM_SHA512_T_HMAC_GENERAL},
    {"CKM_SHA512_T_KEY_DERIVATION", CKM_SHA512_T_KEY_DERIVATION},
    {"CKM_SHA_1", CKM_SHA_1},
    {"CKM_SHA_1_HMAC", CKM_SHA_1_HMAC},
    {"CKM_SHA_1_HMAC_GENERAL", CKM_SHA_1_HMAC_GENERAL},
    {"CKM_SKIPJACK_CBC64", CKM_SKIPJACK_CBC64},
    {"CKM_SKIPJACK_CFB16", CKM_SKIPJACK_CFB16},
    {"CKM_SKIPJACK_CFB32", CKM_SKIPJACK_CFB32},
    {"CKM_SKIPJACK_CFB64", CKM_SKIPJACK_CFB64},
    {"CKM_SKIPJACK_CFB8", CKM_SKIPJACK_CFB8},
    {"CKM_SKIPJACK_ECB64", CKM_SKIPJACK_ECB64},
    {"CKM_SKIPJACK_KEY_GEN", CKM_SKIPJACK_KEY_GEN},
    {"CKM_SKIPJACK_OFB64", CKM_SKIPJACK_OFB64},
    {"CKM_SKIPJACK_PRIVATE_WRAP", CKM_SKIPJACK_PRIVATE_WRAP},
    {"CKM_SKIPJACK_RELAYX", CKM_SKIPJACK_RELAYX},
    {"CKM_SKIPJACK_WRAP", CKM_SKIPJACK_WRAP},
    {"CKM_SSL3_KEY_AND_MAC_DERIVE", CKM_SSL3_KEY_AND_MAC_DERIVE},
    {"CKM_SSL3_MASTER_KEY_DERIVE", CKM_SSL3_MASTER_KEY_DERIVE},
    {"CKM_SSL3_MASTER_KEY_DERIVE_DH", CKM_SSL3_MASTER_KEY_DERIVE_DH},
    {"CKM_SSL3_MD5_MAC", CKM_SSL3_MD5_MAC},
    {"CKM_SSL3_PRE_MASTER_KEY_GEN", CKM_SSL3_PRE_MASTER_KEY_GEN},
    {"CKM_SSL3_SHA1_MAC", CKM_SSL3_SHA1_MAC},
    {"CKM_TLS10_MAC_CLIENT", CKM_TLS10_MAC_CLIENT},
    {"CKM_TLS10_MAC_SERVER", CKM_TLS10_MAC_SERVER},
    {"CKM_TLS12_KDF", CKM_TLS12_KDF},
    {"CKM_TLS12_KEY_AND_MAC_DERIVE", CKM_TLS12_KEY_AND_MAC_DERIVE},
    {"CKM_TLS12_KEY_SAFE_DERIVE", CKM_TLS12_KEY_SAFE_DERIVE},
    {"CKM_TLS12_MAC", CKM_TLS12_MAC},
    {"CKM_TLS12_MASTER_KEY_DERIVE", CKM_TLS12_MASTER_KEY_DERIVE},
    {"CKM_TLS12_MASTER_KEY_DERIVE_DH", CKM_TLS12_MASTER_KEY_DERIVE_DH},
    {"CKM_TLS_KDF", CKM_TLS_KDF},
    {"CKM_TLS_KEY_AND_MAC_DERIVE", CKM_TLS_KEY_AND_MAC_DERIVE},
    {"CKM_TLS_MAC", CKM_TLS_MAC},
    {"CKM_TLS_MASTER_KEY_DERIVE", CKM_TLS_MASTER_KEY_DERIVE},
    {"CKM_TLS_MASTER_KEY_DERIVE_DH", CKM_TLS_MASTER_KEY_DERIVE_DH},
    {"CKM_TLS_PRE_MASTER_KEY_GEN", CKM_TLS_PRE_MASTER_KEY_GEN},
    {"CKM_TLS_PRF", CKM_TLS_PRF},
    {"CKM_TWOFISH_CBC", CKM_TWOFISH_CBC},
    {"CKM_TWOFISH_CBC_PAD", CKM_TWOFISH_CBC_PAD},
    {"CKM_TWOFISH_KEY_GEN", CKM_TWOFISH_KEY_GEN},
    {"CKM_VENDOR_DEFINED", CKM_VENDOR_DEFINED},
    {"CKM_WTLS_CLIENT_KEY_AND_MAC_DERIVE", CKM_WTLS_CLIENT_KEY_AND_MAC_DERIVE},
    {"CKM_WTLS_MASTER_KEY_DERIVE", CKM_WTLS_MASTER_KEY_DERIVE},
    {"CKM_WTLS_MASTER_KEY_DERIVE_DH_ECC", CKM_WTLS_MASTER_KEY_DERIVE_DH_ECC},
    {"CKM_WTLS_PRE_MASTER_KEY_GEN", CKM_WTLS_PRE_MASTER_KEY_GEN},
    {"CKM_WTLS_PRF", CKM_WTLS_PRF},
    {"CKM_WTLS_SERVER_KEY_AND_MAC_DERIVE", CKM_WTLS_SERVER_KEY_AND_MAC_DERIVE},
    {"CKM_X9_42_DH_DERIVE", CKM_X9_42_DH_DERIVE},
    {"CKM_X9_42_DH_HYBRID_DERIVE", CKM_X9_42_DH_HYBRID_DERIVE},
    {"CKM_X9_42_DH_KEY_PAIR_GEN", CKM_X9_42_DH_KEY_PAIR_GEN},
    {"CKM_X9_42_DH_PARAMETER_GEN", CKM_X9_42_DH_PARAMETER_GEN},
    {"CKM_X9_42_MQV_DERIVE", CKM_X9_42_MQV_DERIVE},
    {"CKM_XEDDSA", CKM_XEDDSA},
    {"CKM_XOR_BASE_AND_DATA", CKM_XOR_BASE_AND_DATA},
    {"CKN_OTP_CHANGED", CKN_OTP_CHANGED},
    {"CKN_SURRENDER", CKN_SURRENDER},
    {"CKO_CERTIFICATE", CKO_CERTIFICATE},
    {"CKO_DATA", CKO_DATA},
    {"CKO_DOMAIN_PARAMETERS", CKO_DOMAIN_PARAMETERS},
    {"CKO_HW_FEATURE", CKO_HW_FEATURE},
    {"CKO_MECHANISM", CKO_MECHANISM},
    {"CKO_OTP_KEY", CKO_OTP_KEY},
    {"CKO_PRIVATE_KEY", CKO_PRIVATE_KEY},
    {"CKO_PROFILE", CKO_PROFILE},
    {"CKO_PUBLIC_KEY", CKO_PUBLIC_KEY},
    {"CKO_SECRET_KEY", CKO_SECRET_KEY},
    {"CKO_VENDOR_DEFINED", CKO_VENDOR_DEFINED},
    {"CKP_AUTHENTICATION_TOKEN", CKP_AUTHENTICATION_TOKEN},
    {"CKP_BASELINE_PROVIDER", CKP_BASELINE_PROVIDER},
    {"CKP_EXTENDED_PROVIDER", CKP_EXTENDED_PROVIDER},
    {"CKP_INVALID_ID", CKP_INVALID_ID},
    {"CKP_PUBLIC_CERTIFICATES_TOKEN", CKP_PUBLIC_CERTIFICATES_TOKEN},
    {"CKP_VENDOR_DEFINED", CKP_VENDOR_DEFINED},
    {"CKR_ACTION_PROHIBITED", CKR_ACTION_PROHIBITED},
    {"CKR_ARGUMENTS_BAD", CKR_ARGUMENTS_BAD},
    {"CKR_ATTRIBUTE_READ_ONLY", CKR_ATTRIBUTE_READ_ONLY},
    {"CKR_ATTRIBUTE_SENSITIVE", CKR_ATTRIBUTE_SENSITIVE},
    {"CKR_ATTRIBUTE_TYPE_INVALID", CKR_ATTRIBUTE_TYPE_INVALID},
    {"CKR_ATTRIBUTE_VALUE_INVALID", CKR_ATTRIBUTE_VALUE_INVALID},
    {"CKR_BUFFER_TOO_SMALL", CKR_BUFFER_TOO_SMALL},
    {"CKR_CANCEL", CKR_CANCEL},
    {"CKR_CANT_LOCK", CKR_CANT_LOCK},
    {"CKR_CRYPTOKI_ALREADY_INITIALIZED", CKR_CRYPTOKI_ALREADY_INITIALIZED},
    {"CKR_CRYPTOKI_NOT_INITIALIZED", CKR_CRYPTOKI_NOT_INITIALIZED},
    {"CKR_CURVE_NOT_SUPPORTED", CKR_CURVE_NOT_SUPPORTED},
    {"CKR_DATA_INVALID", CKR_DATA_INVALID},
    {"CKR_DATA_LEN_RANGE", CKR_DATA_LEN_RANGE},
    {"CKR_DEVICE_ERROR", CKR_DEVICE_ERROR},
    {"CKR_DEVICE_MEMORY", CKR_DEVICE_MEMORY},
    {"CKR_DEVICE_REMOVED", CKR_DEVICE_REMOVED},
    {"CKR_DOMAIN_PARAMS_INVALID", CKR_DOMAIN_PARAMS_INVALID},
    {"CKR_ENCRYPTED_DATA_INVALID", CKR_ENCRYPTED_DATA_INVALID},
    {"CKR_ENCRYPTED_DATA_LEN_RANGE", CKR_ENCRYPTED_DATA_LEN_RANGE},
    {"CKR_EXCEEDED_MAX_ITERATIONS", CKR_EXCEEDED_MAX_ITERATIONS},
    {"CKR_FIPS_SELF_TEST_FAILED", CKR_FIPS_SELF_TEST_FAILED},
    {"CKR_FUNCTION_CANCELED", CKR_FUNCTION_CANCELED},
    {"CKR_FUNCTION_FAILED", CKR_FUNCTION_FAILED},
    {"CKR_FUNCTION_NOT_PARALLEL", CKR_FUNCTION_NOT_PARALLEL},
    {"CKR_FUNCTION_NOT_SUPPORTED", CKR_FUNCTION_NOT_SUPPORTED},
    {"CKR_FUNCTION_REJECTED", CKR_FUNCTION_REJECTED},
    {"CKR_GENERAL_ERROR", CKR_GENERAL_ERROR},
    {"CKR_HOST_MEMORY", CKR_HOST_MEMORY},
    {"CKR_INFORMATION_SENSITIVE", CKR_INFORMATION_SENSITIVE},
    {"CKR_KEY_CHANGED", CKR_KEY_CHANGED},
    {"CKR_KEY_FUNCTION_NOT_PERMITTED", CKR_KEY_FUNCTION_NOT_PERMITTED},
    {"CKR_KEY_HANDLE_INVALID", CKR_KEY_HANDLE_INVALID},
    {"CKR_KEY_INDIGESTIBLE", CKR_KEY_INDIGESTIBLE},
    {"CKR_KEY_NEEDED", CKR_KEY_NEEDED},
    {"CKR_KEY_NOT_NEEDED", CKR_KEY_NOT_NEEDED},
    {"CKR_KEY_NOT_WRAPPABLE", CKR_KEY_NOT_WRAPPABLE},
    {"CKR_KEY_SIZE_RANGE", CKR_KEY_SIZE_RANGE},
    {"CKR_KEY_TYPE_INCONSISTENT", CKR_KEY_TYPE_INCONSISTENT},
    {"CKR_KEY_UNEXTRACTABLE", CKR_KEY_UNEXTRACTABLE},
    {"CKR_LIBRARY_LOAD_FAILED", CKR_LIBRARY_LOAD_FAILED},
    {"CKR_MECHANISM_INVALID", CKR_MECHANISM_INVALID},
    {"CKR_MECHANISM_PARAM_INVALID", CKR_MECHANISM_PARAM_INVALID},
    {"CKR_MUTEX_BAD", CKR_MUTEX_BAD},
    {"CKR_MUTEX_NOT_LOCKED", CKR_MUTEX_NOT_LOCKED},
    {"CKR_NEED_TO_CREATE_THREADS", CKR_NEED_TO_CREATE_THREADS},
    {"CKR_NEW_PIN_MODE", CKR_NEW_PIN_MODE},
    {"CKR_NEXT_OTP", CKR_NEXT_OTP},
    {"CKR_NO_EVENT", CKR_NO_EVENT},
    {"CKR_OBJECT_HANDLE_INVALID", CKR_OBJECT_HANDLE_INVALID},
    {"CKR_OK", CKR_OK},
    {"CKR_OPERATION_ACTIVE", CKR_OPERATION_ACTIVE},
    {"CKR_OPERATION_CANCEL_FAILED", CKR_OPERATION_CANCEL_FAILED},
    {"CKR_OPERATION_NOT_INITIALIZED", CKR_OPERATION_NOT_INITIALIZED},
    {"CKR_PIN_EXPIRED", CKR_PIN_EXPIRED},
    {"CKR_PIN_INCORRECT", CKR_PIN_INCORRECT},
    {"CKR_PIN_INVALID", CKR_PIN_INVALID},
    {"CKR_PIN_LEN_RANGE", CKR_PIN_LEN_RANGE},
    {"CKR_PIN_LOCKED", CKR_PIN_LOCKED},
    {"CKR_PIN_TOO_WEAK", CKR_PIN_TOO_WEAK},
    {"CKR_PUBLIC_KEY_INVALID", CKR_PUBLIC_KEY_INVALID},
    {"CKR_RANDOM_NO_RNG", CKR_RANDOM_NO_RNG},
    {"CKR_RANDOM_SEED_NOT_SUPPORTED", CKR_RANDOM_SEED_NOT_SUPPORTED},
    {"CKR_SAVED_STATE_INVALID", CKR_SAVED_STATE_INVALID},
    {"CKR_SESSION_CLOSED", CKR_SESSION_CLOSED},
    {"CKR_SESSION_COUNT", CKR_SESSION_COUNT},
    {"CKR_SESSION_EXISTS", CKR_SESSION_EXISTS},
    {"CKR_SESSION_HANDLE_INVALID", CKR_SESSION_HANDLE_INVALID},
    {"CKR_SESSION_PARALLEL_NOT_SUPPORTED", CKR_SESSION_PARALLEL_NOT_SUPPORTED},
    {"CKR_SESSION_READ_ONLY", CKR_SESSION_READ_ONLY},
    {"CKR_SESSION_READ_ONLY_EXISTS", CKR_SESSION_READ_ONLY_EXISTS},
    {"CKR_SESSION_READ_WRITE_SO_EXISTS", CKR_SESSION_READ_WRITE_SO_EXISTS},
    {"CKR_SIGNATURE_INVALID", CKR_SIGNATURE_INVALID},
    {"CKR_SIGNATURE_LEN_RANGE", CKR_SIGNATURE_LEN_RANGE},
    {"CKR_SLOT_ID_INVALID", CKR_SLOT_ID_INVALID},
    {"CKR_STATE_UNSAVEABLE", CKR_STATE_UNSAVEABLE},
    {"CKR_TEMPLATE_INCOMPLETE", CKR_TEMPLATE_INCOMPLETE},
    {"CKR_TEMPLATE_INCONSISTENT", CKR_TEMPLATE_INCONSISTENT},
    {"CKR_TOKEN_NOT_PRESENT", CKR_TOKEN_NOT_PRESENT},
    {"CKR_TOKEN_NOT_RECOGNIZED", CKR_TOKEN_NOT_RECOGNIZED},
    {"CKR_TOKEN_WRITE_PROTECTED", CKR_TOKEN_WRITE_PROTECTED},
    {"CKR_UNWRAPPING_KEY_HANDLE_INVALID", CKR_UNWRAPPING_KEY_HANDLE_INVALID},
    {"CKR_UNWRAPPING_KEY_SIZE_RANGE", CKR_UNWRAPPING_KEY_SIZE_RANGE},
    {"CKR_UNWRAPPING_KEY_TYPE_INCONSISTENT", CKR_UNWRAPPING_KEY_TYPE_INCONSISTENT},
    {"CKR_USER_ALREADY_LOGGED_IN", CKR_USER_ALREADY_LOGGED_IN},
    {"CKR_USER_ANOTHER_ALREADY_LOGGED_IN", CKR_USER_ANOTHER_ALREADY_LOGGED_IN},
    {"CKR_USER_NOT_LOGGED_IN", CKR_USER_NOT_LOGGED_IN},
    {"CKR_USER_PIN_NOT_INITIALIZED", CKR_USER_PIN_NOT_INITIALIZED},
    {"CKR_USER_TOO_MANY_TYPES", CKR_USER_TOO_MANY_TYPES},
    {"CKR_USER_TYPE_INVALID", CKR_USER_TYPE_INVALID},
    {"CKR_VENDOR_DEFINED", CKR_VENDOR_DEFINED},
    {"CKR_WRAPPED_KEY_INVALID", CKR_WRAPPED_KEY_INVALID},
    {"CKR_WRAPPED_KEY_LEN_RANGE", CKR_WRAPPED_KEY_LEN_RANGE},
    {"CKR_WRAPPING_KEY_HANDLE_INVALID", CKR_WRAPPING_KEY_HANDLE_INVALID},
    {"CKR_WRAPPING_KEY_SIZE_RANGE", CKR_WRAPPING_KEY_SIZE_RANGE},
    {"CKR_WRAPPING_KEY_TYPE_INCONSISTENT", CKR_WRAPPING_KEY_TYPE_INCONSISTENT},
    {"CKS_RO_PUBLIC_SESSION", CKS_RO_PUBLIC_SESSION},
    {"CKS_RO_USER_FUNCTIONS", CKS_RO_USER_FUNCTIONS},
    {"CKS_RW_PUBLIC_SESSION", CKS_RW_PUBLIC_SESSION},
    {"CKS_RW_SO_FUNCTIONS", CKS_RW_SO_FUNCTIONS},
    {"CKS_RW_USER_FUNCTIONS", CKS_RW_USER_FUNCTIONS},
    {"CKU_CONTEXT_SPECIFIC", CKU_CONTEXT_SPECIFIC},
    {"CKU_SO", CKU_SO},
    {"CKU_USER", CKU_USER},
    {"CKZ_DATA_SPECIFIED", CKZ_DATA_SPECIFIED},
    {"CK_EFFECTIVELY_INFINITE", CK_EFFECTIVELY_INFINITE},
    {"CK_INVALID_HANDLE", CK_INVALID_HANDLE},
    {"CK_OTP_CHALLENGE", CK_OTP_CHALLENGE},
    {"CK_OTP_COUNTER", CK_OTP_COUNTER},
    {"CK_OTP_FLAGS", CK_OTP_FLAGS},
    {"CK_OTP_FORMAT", CK_OTP_FORMAT},
    {"CK_OTP_FORMAT_ALPHANUMERIC", CK_OTP_FORMAT_ALPHANUMERIC},
    {"CK_OTP_FORMAT_BINARY", CK_OTP_FORMAT_BINARY},
    {"CK_OTP_FORMAT_DECIMAL", CK_OTP_FORMAT_DECIMAL},
    {"CK_OTP_FORMAT_HEXADECIMAL", CK_OTP_FORMAT_HEXADECIMAL},
    {"CK_OTP_OUTPUT_LENGTH", CK_OTP_OUTPUT_LENGTH},
    {"CK_OTP_PARAM_IGNORED", CK_OTP_PARAM_IGNORED},
    {"CK_OTP_PARAM_MANDATORY", CK_OTP_PARAM_MANDATORY},
    {"CK_OTP_PARAM_OPTIONAL", CK_OTP_PARAM_OPTIONAL},
    {"CK_OTP_PIN", CK_OTP_PIN},
    {"CK_OTP_TIME", CK_OTP_TIME},
    {"CK_OTP_VALUE", CK_OTP_VALUE},
    {"CK_UNAVAILABLE_INFORMATION", CK_UNAVAILABLE_INFORMATION},
    {NULL, 0}
};

typedef struct {
    const char *key;
    unsigned long value;
} HashEntry;

static HashEntry hash_table[HASH_SIZE] = {{NULL, 0}};

static unsigned int djb2_hash(const char *str) {
    unsigned int hash = 5381;
    int c;

    while ((c = *str++))
        hash = ((hash << 5) + hash) + c;

    return hash % HASH_SIZE;
}

static void init_hash_table() {
    static char init = 0;
    if (init)
        return;

    for (int i = 0; type_table[i].name != NULL; i++) {
        unsigned int index = djb2_hash(type_table[i].name);
        while (hash_table[index].key != NULL)
            index = (index + 1) % HASH_SIZE;
        hash_table[index].key = type_table[i].name;
        hash_table[index].value = type_table[i].value;
    }

    init = 1;
}

unsigned long get_type_value(const unsigned char *type_name) {
    init_hash_table();

    unsigned int index = djb2_hash((const char *)type_name);
    while (hash_table[index].key != NULL) {
        if (strcmp(hash_table[index].key, (const char *)type_name) == 0) {
            return hash_table[index].value;
        }
        index = (index + 1) % HASH_SIZE;
    }

    janet_panicf("%s type is not found", type_name);
    return -1;
}


p11_attr_type_t get_attribute_type(CK_ATTRIBUTE_TYPE type) {
    switch (type) {
        /* Boolean attributes */
        case CKA_TOKEN:
        case CKA_PRIVATE:
        case CKA_TRUSTED:
        case CKA_SENSITIVE:
        case CKA_ENCRYPT:
        case CKA_DECRYPT:
        case CKA_WRAP:
        case CKA_UNWRAP:
        case CKA_SIGN:
        case CKA_SIGN_RECOVER:
        case CKA_VERIFY:
        case CKA_VERIFY_RECOVER:
        case CKA_DERIVE:
        case CKA_EXTRACTABLE:
        case CKA_LOCAL:
        case CKA_NEVER_EXTRACTABLE:
        case CKA_ALWAYS_SENSITIVE:
        case CKA_MODIFIABLE:
        case CKA_COPYABLE:
        case CKA_DESTROYABLE:
        case CKA_ALWAYS_AUTHENTICATE:
        case CKA_WRAP_WITH_TRUSTED:
        case CKA_RESET_ON_INIT:
        case CKA_HAS_RESET:
        case CKA_COLOR:
        case CKA_OTP_USER_FRIENDLY_MODE:
            return P11_ATTR_BOOL;

        /* CK_ULONG attributes */
        case CKA_CERTIFICATE_TYPE:
        case CKA_CERTIFICATE_CATEGORY:
        case CKA_MECHANISM_TYPE:
        case CKA_KEY_TYPE:
        case CKA_KEY_GEN_MECHANISM:
        case CKA_CLASS:
        case CKA_MODULUS_BITS:
        case CKA_VALUE_BITS:
        case CKA_VALUE_LEN:
        case CKA_PRIME_BITS:
        case CKA_SUB_PRIME_BITS:
        case CKA_PIXEL_X:
        case CKA_PIXEL_Y:
        case CKA_RESOLUTION:
        case CKA_CHAR_ROWS:
        case CKA_CHAR_COLUMNS:
        case CKA_BITS_PER_PIXEL:
        case CKA_PROFILE_ID:
        case CKA_OTP_LENGTH:
        case CKA_OTP_TIME_INTERVAL:
        case CKA_OTP_CHALLENGE_REQUIREMENT:
        case CKA_OTP_TIME_REQUIREMENT:
        case CKA_OTP_COUNTER_REQUIREMENT:
        case CKA_OTP_PIN_REQUIREMENT:
        case CKA_HW_FEATURE_TYPE:
            return P11_ATTR_ULONG;

        /* Date attributes */
        case CKA_START_DATE:
        case CKA_END_DATE:
            return P11_ATTR_DATE;

        /* Byte array attributes */
        case CKA_VALUE:
        case CKA_OBJECT_ID:
        case CKA_SUBJECT:
        case CKA_ID:
        case CKA_ISSUER:
        case CKA_SERIAL_NUMBER:
        case CKA_AC_ISSUER:
        case CKA_OWNER:
        case CKA_ATTR_TYPES:
        case CKA_ALLOWED_MECHANISMS:
        case CKA_BASE:
        case CKA_PRIME:
        case CKA_PRIME_1:
        case CKA_PRIME_2:
        case CKA_EXPONENT_1:
        case CKA_EXPONENT_2:
        case CKA_COEFFICIENT:
        case CKA_MODULUS:
        case CKA_PUBLIC_EXPONENT:
        case CKA_PRIVATE_EXPONENT:
        case CKA_EC_PARAMS:
        case CKA_EC_POINT:
        case CKA_CHECK_VALUE:
        case CKA_GOST28147_PARAMS:
        case CKA_GOSTR3410_PARAMS:
        case CKA_GOSTR3411_PARAMS:
        case CKA_WRAP_TEMPLATE:
        case CKA_UNWRAP_TEMPLATE:
        case CKA_DERIVE_TEMPLATE:
        case CKA_OTP_COUNTER:
        case CKA_OTP_SERVICE_LOGO:
        case CKA_PUBLIC_KEY_INFO:
        case CKA_DEFAULT_CMS_ATTRIBUTES:
        case CKA_HASH_OF_ISSUER_PUBLIC_KEY:
        case CKA_HASH_OF_SUBJECT_PUBLIC_KEY:
        case CKA_REQUIRED_CMS_ATTRIBUTES:
        case CKA_SUBPRIME:
        case CKA_SUPPORTED_CMS_ATTRIBUTES:
            return P11_ATTR_BYTES;

        /* String attributes (null-terminated) */
        case CKA_LABEL:
        case CKA_APPLICATION:
        case CKA_URL:
        case CKA_CHAR_SETS:
        case CKA_ENCODING_METHODS:
        case CKA_MIME_TYPES:
        case CKA_JAVA_MIDP_SECURITY_DOMAIN:
        case CKA_NAME_HASH_ALGORITHM:
        case CKA_OTP_FORMAT:
        case CKA_OTP_SERVICE_IDENTIFIER:
        case CKA_OTP_SERVICE_LOGO_TYPE:
        case CKA_OTP_USER_IDENTIFIER:
        case CKA_OTP_TIME:
            return P11_ATTR_STRING;

        default:
            janet_panicf("0x%0x type is not supported", type);
    }

    return P11_ATTR_STRING;
}

const char *p11_attr_type_to_string(CK_ATTRIBUTE_TYPE type) {
    switch(type) {
        case CKA_AC_ISSUER: return "CKA_AC_ISSUER";
        case CKA_ALLOWED_MECHANISMS: return "CKA_ALLOWED_MECHANISMS";
        case CKA_ALWAYS_AUTHENTICATE: return "CKA_ALWAYS_AUTHENTICATE";
        case CKA_ALWAYS_SENSITIVE: return "CKA_ALWAYS_SENSITIVE";
        case CKA_APPLICATION: return "CKA_APPLICATION";
        case CKA_ATTR_TYPES: return "CKA_ATTR_TYPES";
        case CKA_BASE: return "CKA_BASE";
        case CKA_BITS_PER_PIXEL: return "CKA_BITS_PER_PIXEL";
        case CKA_CERTIFICATE_CATEGORY: return "CKA_CERTIFICATE_CATEGORY";
        case CKA_CERTIFICATE_TYPE: return "CKA_CERTIFICATE_TYPE";
        case CKA_CHAR_COLUMNS: return "CKA_CHAR_COLUMNS";
        case CKA_CHAR_ROWS: return "CKA_CHAR_ROWS";
        case CKA_CHAR_SETS: return "CKA_CHAR_SETS";
        case CKA_CHECK_VALUE: return "CKA_CHECK_VALUE";
        case CKA_CLASS: return "CKA_CLASS";
        case CKA_COEFFICIENT: return "CKA_COEFFICIENT";
        case CKA_COLOR: return "CKA_COLOR";
        case CKA_COPYABLE: return "CKA_COPYABLE";
        case CKA_DECRYPT: return "CKA_DECRYPT";
        case CKA_DEFAULT_CMS_ATTRIBUTES: return "CKA_DEFAULT_CMS_ATTRIBUTES";
        case CKA_DERIVE: return "CKA_DERIVE";
        case CKA_DESTROYABLE: return "CKA_DESTROYABLE";
        case CKA_EC_PARAMS: return "CKA_EC_PARAMS";
        case CKA_EC_POINT: return "CKA_EC_POINT";
        case CKA_ENCODING_METHODS: return "CKA_ENCODING_METHODS";
        case CKA_ENCRYPT: return "CKA_ENCRYPT";
        case CKA_END_DATE: return "CKA_END_DATE";
        case CKA_EXPONENT_2: return "CKA_EXPONENT_2";
        case CKA_EXTRACTABLE: return "CKA_EXTRACTABLE";
        case CKA_HASH_OF_ISSUER_PUBLIC_KEY: return "CKA_HASH_OF_ISSUER_PUBLIC_KEY";
        case CKA_HASH_OF_SUBJECT_PUBLIC_KEY: return "CKA_HASH_OF_SUBJECT_PUBLIC_KEY";
        case CKA_HAS_RESET: return "CKA_HAS_RESET";
        case CKA_HW_FEATURE_TYPE: return "CKA_HW_FEATURE_TYPE";
        case CKA_ID: return "CKA_ID";
        case CKA_ISSUER: return "CKA_ISSUER";
        case CKA_JAVA_MIDP_SECURITY_DOMAIN: return "CKA_JAVA_MIDP_SECURITY_DOMAIN";
        case CKA_KEY_GEN_MECHANISM: return "CKA_KEY_GEN_MECHANISM";
        case CKA_KEY_TYPE: return "CKA_KEY_TYPE";
        case CKA_LABEL: return "CKA_LABEL";
        case CKA_LOCAL: return "CKA_LOCAL";
        case CKA_MECHANISM_TYPE: return "CKA_MECHANISM_TYPE";
        case CKA_MIME_TYPES: return "CKA_MIME_TYPES";
        case CKA_MODIFIABLE: return "CKA_MODIFIABLE";
        case CKA_MODULUS: return "CKA_MODULUS";
        case CKA_MODULUS_BITS: return "CKA_MODULUS_BITS";
        case CKA_NAME_HASH_ALGORITHM: return "CKA_NAME_HASH_ALGORITHM";
        case CKA_NEVER_EXTRACTABLE: return "CKA_NEVER_EXTRACTABLE";
        case CKA_OBJECT_ID: return "CKA_OBJECT_ID";
        case CKA_OWNER: return "CKA_OWNER";
        case CKA_PIXEL_X: return "CKA_PIXEL_X";
        case CKA_PIXEL_Y: return "CKA_PIXEL_Y";
        case CKA_PRIME: return "CKA_PRIME";
        case CKA_PRIME_2: return "CKA_PRIME_2";
        case CKA_PRIME_BITS: return "CKA_PRIME_BITS";
        case CKA_PRIVATE: return "CKA_PRIVATE";
        case CKA_PRIVATE_EXPONENT: return "CKA_PRIVATE_EXPONENT";
        case CKA_PUBLIC_EXPONENT: return "CKA_PUBLIC_EXPONENT";
        case CKA_REQUIRED_CMS_ATTRIBUTES: return "CKA_REQUIRED_CMS_ATTRIBUTES";
        case CKA_RESET_ON_INIT: return "CKA_RESET_ON_INIT";
        case CKA_RESOLUTION: return "CKA_RESOLUTION";
        case CKA_SENSITIVE: return "CKA_SENSITIVE";
        case CKA_SERIAL_NUMBER: return "CKA_SERIAL_NUMBER";
        case CKA_SIGN: return "CKA_SIGN";
        case CKA_SIGN_RECOVER: return "CKA_SIGN_RECOVER";
        case CKA_START_DATE: return "CKA_START_DATE";
        case CKA_SUBJECT: return "CKA_SUBJECT";
        case CKA_SUBPRIME: return "CKA_SUBPRIME";
        case CKA_SUPPORTED_CMS_ATTRIBUTES: return "CKA_SUPPORTED_CMS_ATTRIBUTES";
        case CKA_TOKEN: return "CKA_TOKEN";
        case CKA_TRUSTED: return "CKA_TRUSTED";
        case CKA_UNWRAP: return "CKA_UNWRAP";
        case CKA_UNWRAP_TEMPLATE: return "CKA_UNWRAP_TEMPLATE";
        case CKA_URL: return "CKA_URL";
        case CKA_VALUE: return "CKA_VALUE";
        case CKA_VALUE_BITS: return "CKA_VALUE_BITS";
        case CKA_VALUE_LEN: return "CKA_VALUE_LEN";
        case CKA_VENDOR_DEFINED: return "CKA_VENDOR_DEFINED";
        case CKA_VERIFY: return "CKA_VERIFY";
        case CKA_VERIFY_RECOVER: return "CKA_VERIFY_RECOVER";
        case CKA_WRAP: return "CKA_WRAP";
        case CKA_WRAP_TEMPLATE: return "CKA_WRAP_TEMPLATE";
        case CKA_WRAP_WITH_TRUSTED: return "CKA_WRAP_WITH_TRUSTED";
        default:
            janet_panicf("0x%lx type is not found.", type);
    }
}
