name: Test and deploy site

on:
  push:
    branches: [ main ]

jobs:
  test-and-deploy-site:
    name: Test and deploy site
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
    - uses: ConorMacBride/install-package@v1
      with:
        apt: softhsm2
    - name: "Checkout main"
      uses: actions/checkout@v4
    - name: "Test project"
      uses: pyrmont/action-janet-test@v5
    - name: "Install mendoza"
      run: |
        $PREFIX/bin/jpm install mendoza
    - name: "Generate site"
      run: |
        mdz clean
        mdz build docs
    - name: "Checkout gh-pages"
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages-worktree
    - name: "Commit and push changes"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        SOURCE_MSG=$(git -C "$GITHUB_WORKSPACE" log -1 --pretty=%s)
        SOURCE_SHA=$(git -C "$GITHUB_WORKSPACE" rev-parse --short HEAD)
        cd gh-pages-worktree
        git config user.name github-actions
        git config user.email github-actions@github.com
        rm -rf docs
        cp -r ../docs docs
        git add docs
        git commit -m "Site: ${SOURCE_MSG} (${SOURCE_SHA})" || echo "nothing to commit"
        git push https://${GITHUB_ACTOR}:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git gh-pages
